import client from './client'

export const getAdminDashboard = () => client.get('/admin/dashboard/')
export const getAdminCustomers = () => client.get('/admin/customers/')
export const getAdminCustomer = (id) => client.get(`/admin/customers/${id}/`)
export const updateCustomer = (id, data) => client.patch(`/admin/customers/${id}/`, data)
export const adjustCredit = (id, credit_score) => client.post(`/admin/customers/${id}/adjust-credit/`, { credit_score })
export const updateLoanSettings = (data) => client.post('/admin/loan-settings/', data)
export const getAdminAgents = () => client.get('/admin/agents/')
export const generateInvite = () => client.post('/admin/agents/invite/')
export const getAgentDetail = (id) => client.get(`/admin/agents/${id}/`)
export const editAgent = (id, data) => client.patch(`/admin/agents/${id}/edit/`, data)
export const giveAgentMoney = (id, amount) => client.post(`/admin/agents/${id}/give-money/`, { amount })
export const getAgentTransactions = (id) => client.get(`/admin/agents/${id}/transactions/`)
export const getAgentPerformance = (id, period) => client.get(`/admin/agents/${id}/performance/`, { params: { period } })
export const getAgentLoans = (id, loan_status) => client.get(`/admin/agents/${id}/loans/${loan_status}/`)
export const agentWithdrawRequest = (id, amount) => client.post(`/admin/agents/${id}/withdraw/`, { amount })
export const approveTransaction = (reqId, data) => client.post(`/admin/transaction/${reqId}/approve/`, data)
export const getAdminFinance = () => client.get('/admin/finance/')
export const deposit = (amount, note) => client.post('/admin/finance/deposit/', { amount, note })
export const withdraw = (amount, note) => client.post('/admin/finance/withdraw/', { amount, note })
export const dismissNotification = (pk) => client.post(`/admin/notification/${pk}/dismiss/`)
export const deleteLoan = (loanId) => client.delete(`/admin/loans/${loanId}/delete/`)
